# Generated by Django 5.2.3 on 2025-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('shift_date', models.DateField()),
                ('shift_slot', models.CharField(max_length=20)),
                ('scheduled_staff', models.IntegerField()),
                ('present_staff', models.IntegerField()),
                ('patient_count', models.IntegerField(default=0)),
                ('avg_patient_acuity', models.FloatField(default=0.0)),
                ('emergencies_count', models.IntegerField(default=0)),
                ('leaves_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
